### ISSUE TITLE
Problem with Blender 2.69

### ISSUE THREAD

**Issue by wasimbeniwale** [xml3d/Blender-Exporter#2]
![xml3d export problem](https://cloud.githubusercontent.com/assets/5242262/5586374/f5b0b78e-90f1-11e4-8d02-3f75363abc9f.jpg)
Error while exporting to xml3d in blender version 2.69 running on 64 bit ubuntu.

**Comment by NicolasGoeddel** [comment]
Unfortunanlity I am no more sitting in on that xml3d project. I guess there were some changes in blender since version 2.62 and now the exporter does not run anymore. Maybe some other guys can help you.

**Comment by wasimbeniwale** [comment]
Thanks brother.
